## 1. Create a player¶
Create a player. The dictionary and list variables should just be defined as empty at this point.

The player variables are:
player_id : id code unique to each player (integer)
player_name : entered name of the player (string)
time_played : number of time played the game in minutes (float)
player_pokemon: the player's captured pokemon (dictionary)
gyms_visited: ids of the gyms that a player has visited (list)

In [1]:
players = {'player_id' : 555, 'player_name' : "DavidJ", 'time_played':  12.2, 'player_pokemon' : (), 'gyms_visited' : []}
print players.keys()
print players

['player_id', 'time_played', 'gyms_visited', 'player_name', 'player_pokemon']
{'player_id': 555, 'time_played': 12.2, 'gyms_visited': [], 'player_name': 'DavidJ', 'player_pokemon': ()}


## 2. Defining "gym" locations¶
Copy and paste listing from assignment into new list. Because # of locations is small, I just manually updated the list contents for Python (remove leading index # and period and then added commas. Kept to single line per entry to make proofing easier

In [2]:
gym_list =['reddit.com'
,'amazon.com'
,'twitter.com'
,'linkedin.com'
,'ebay.com'
,'netflix.com'
,'amazon.com'
,'stackoverflow.com'
,'github.com'
,'quora.com']


In [3]:
# Confirm list entry:
gym_list

['reddit.com',
 'amazon.com',
 'twitter.com',
 'linkedin.com',
 'ebay.com',
 'netflix.com',
 'amazon.com',
 'stackoverflow.com',
 'github.com',
 'quora.com']

In [4]:
# confirm type is equal to list
type(gym_list)

list

#### add two locations to my player

In [5]:
players['gyms_visited']= gym_list[4:6]

In [6]:
print players

{'player_id': 555, 'time_played': 12.2, 'gyms_visited': ['ebay.com', 'netflix.com'], 'player_name': 'DavidJ', 'player_pokemon': ()}


## Create pokedex

In [7]:
pokedex = {
'pokemon_id' : int      # unique identifier for each pokemon (integer)
,'name' : str            # the name of the pokemon (string)
,'type' : str            # the category of pokemon (string)
,'hp' : int              # base hitpoints (integer)
,'attack' : int          # base attack (integer)
,'defense' : int         # base defense (integer)
,'special_attack' : int  # base special attack (integer)
,'special_defense' : int # base sepecial defense (integer)
,'speed' : int           # base speed (integer)
}

In [8]:
pokedex

{'attack': int,
 'defense': int,
 'hp': int,
 'name': str,
 'pokemon_id': int,
 'special_attack': int,
 'special_defense': int,
 'speed': int,
 'type': str}

#### We are only going to create 3 different pokemon with these pokemon_id and pokemon_name values:
1 : 'charmander'
2 : 'squirtle'
3 : 'bulbasaur'

In [9]:
pokedex['pokemon_id'] = [1,2,3]
pokedex['name'] =['charmander','squirtle', 'bulbasaur']
pokedex['type'] = ['fire', 'water', 'poison']
pokedex['defense'] = [12,19,117]
pokedex['attack'] = [14, 9, 1]
pokedex['hp'] = [117, 489, 1248]
pokedex['special_attack'] = [6, 12, 9]
pokedex['special_defense'] = [4, 18, 7]
pokedex['speed'] = [45, 33, 89]

In [10]:
pokedex

{'attack': [14, 9, 1],
 'defense': [12, 19, 117],
 'hp': [117, 489, 1248],
 'name': ['charmander', 'squirtle', 'bulbasaur'],
 'pokemon_id': [1, 2, 3],
 'special_attack': [6, 12, 9],
 'special_defense': [4, 18, 7],
 'speed': [45, 33, 89],
 'type': ['fire', 'water', 'poison']}

### 4. Create a data structure for players¶
In order to maintain a database of multiple players, create a dictionary that keeps track of players indexed by player_id.

4.1 
The keys of the dictionary will be player_id and values will be dictionaries containing each player's variables (from question 1). The values in the player's dictionary will be the variables you assigned in question 1.
Construct the players dictionary and insert the player that you defined in question 1, then print players.

In [11]:
player_dict = {players['player_id'] : players}

In [12]:
type(player_dict)

dict

In [13]:
player_dict

{555: {'gyms_visited': ['ebay.com', 'netflix.com'],
  'player_id': 555,
  'player_name': 'DavidJ',
  'player_pokemon': (),
  'time_played': 12.2}}

#### How do I remove player_id from the dict above?

## 4.2
Create a new player with player_id = 2 in the players dictionary. 
Leave the 'player_pokemon' dictionary empty. Append 'stackoverflow.com' and 'github.com' to the 'gyms_visited' list for player 2.

The 'player_name' and 'time_played' values are up to you, but must be a string and float, respectively.

Remember, the player_id is the key for the player in the players dictionary.
Print the players dictionary with the new player inserted.

In [14]:
player_dict[777] = {'player_id' : 777, 'player_name': "new kid in town",'time_played' : 19.7}

# note - an alternative method to add a new dictionary entry would be 
#    player_dict.update(key1: key1 value, key2 : key2 value . . .) 

In [15]:
player_dict

{555: {'gyms_visited': ['ebay.com', 'netflix.com'],
  'player_id': 555,
  'player_name': 'DavidJ',
  'player_pokemon': (),
  'time_played': 12.2},
 777: {'player_id': 777,
  'player_name': 'new kid in town',
  'time_played': 19.7}}

In [16]:
player_dict[777]['gyms_visited'] = ['stackoverflow.com', 'github.com']

In [17]:
player_dict

{555: {'gyms_visited': ['ebay.com', 'netflix.com'],
  'player_id': 555,
  'player_name': 'DavidJ',
  'player_pokemon': (),
  'time_played': 12.2},
 777: {'gyms_visited': ['stackoverflow.com', 'github.com'],
  'player_id': 777,
  'player_name': 'new kid in town',
  'time_played': 19.7}}

## 5. Add captured pokemon for each player¶
The 'player_pokemon' keyed dictionaries for each player keep track of which of the pokemon each player has.

The keys of the 'player_pokemon' dictionaries are the pokemon ids that correspond to the ids in the pokedex dictionary you created earlier.  The values are integers specifying the stats for the pokemon.

Give player 1 a squirtle. (this is my player id 555) Give player 2 charmander and a bulbasaur (this is my player id 777).

Print the players dictionary after adding the pokemon for each player.


In [18]:
player_dict[555]['player_pokemon'] = ['squirtle']
player_dict[777]['player_pokemon'] = ['charmander', 'bulbasaur']


In [19]:
player_dict

{555: {'gyms_visited': ['ebay.com', 'netflix.com'],
  'player_id': 555,
  'player_name': 'DavidJ',
  'player_pokemon': ['squirtle'],
  'time_played': 12.2},
 777: {'gyms_visited': ['stackoverflow.com', 'github.com'],
  'player_id': 777,
  'player_name': 'new kid in town',
  'player_pokemon': ['charmander', 'bulbasaur'],
  'time_played': 19.7}}

## What is connection of player_pokemon to the pokedex? - it looked like I should return a dict for the player pokemon key value





In [20]:
#

## 6. What gyms have players visited?¶
Write a for-loop that:
Iterates through the pokemon_gyms list of gym locations you defined before.

For each gym, iterate through each player in the players dictionary with a second, internal for-loop.

If the player has visited the gym, print out "[player] has visited [gym location].", filling in [player] and [gym location] with the current player's name and current gym location.

## 7. Calculate player "power".
Define a function that will calculate a player's "power". Player power is defined as the sum of the base statistics all of their pokemon.

Your function will:

Accept the players dictionary, pokedex dictionary, and a player_id as arguments.

For the specified player_id, look up that player's pokemon and their level(s).

Find and aggregate the attack and defense values for each of the player's pokemon from the pokedex dictionary.

Print "[player name]'s power is [player power].", where the player power is the sum of the base statistics for all of their pokemon.

Return the player's power value.

Print out the pokemon power for each of your players.
 Example output:

 Ash's power is 57.
 57
 Brock's power is 119.
 119

## 8.1 Load a pokedex file containing all the pokemon¶

Now we have access to the raw base stats on all of the pokemon, scraped from the web.
The provided code below loads information from a comma separated value (csv) file. You need to parse this string into a more useable format. The format of the string is:

***Rows are separated by newline characters: \n

***Columns are separated by commas: ,

***All cells in the csv are double quoted. Ex: "PokedexNumber" is the first cell of the first row.

Using for-loops, create a list of lists where each list within the overall list is a row of the csv/matrix, and each element in that list is a cell in that row. Additional criteria:

Quotes are removed from each cell item.

Numeric column values are converted to floats.

There are some cells that are empty and have no information. For these cells put a -1 value in place.

The first three lists in your pokedex list should look like so:
['PokedexNumber', 'Name', 'Type', 'Total', 'HP', 'Attack', 'Defense', 'SpecialAttack', 'SpecialDefense', 'Speed']
[1.0, 'Bulbasaur', 'GrassPoison', 318.0, 45.0, 49.0, 49.0, 65.0, 65.0, 45.0]
[2.0, 'Ivysaur', 'GrassPoison', 405.0, 60.0, 62.0, 63.0, 80.0, 80.0, 60.0]

In [21]:
import pandas as pd
# pokedex_djs = pd.read_csv('/Users/DavidStier/Documents/Python and Data Science/DSI Class/Downloaded Files/DSI-SF-3-master/datasets/pokemon/pokedex_basic.csv')


# Code to read in pokedex info
raw_pd = ''
pokedex_file = '/Users/DavidStier/Documents/Python and Data Science/DSI Class/Downloaded Files/DSI-SF-3-master/datasets/pokemon/pokedex_basic.csv'
with open(pokedex_file, 'r') as f:
    raw_pd = f.read()
    
# the pokedex string is assigned to the raw_pd variable

In [22]:
raw_pd[:200]

'"PokedexNumber","Name","Type","Total","HP","Attack","Defense","SpecialAttack","SpecialDefense","Speed"\n"001","Bulbasaur","GrassPoison","318","45","49","49","65","65","45"\n"002","Ivysaur","GrassPoison"'

In [252]:
counter = 0
with open(pokedex_file, 'r') as f:
    for line in f:
        print line
        counter +=1
        print "value of counter", counter

"PokedexNumber","Name","Type","Total","HP","Attack","Defense","SpecialAttack","SpecialDefense","Speed"

value of counter 1
"001","Bulbasaur","GrassPoison","318","45","49","49","65","65","45"

value of counter 2
"002","Ivysaur","GrassPoison","405","60","62","63","80","80","60"

value of counter 3
"003","Venusaur","GrassPoison","525","80","82","83","100","100","80"

value of counter 4
"003","VenusaurMega Venusaur","GrassPoison","625","80","100","123","122","120","80"

value of counter 5
"004","Charmander","Fire","309","39","52","43","60","50","65"

value of counter 6
"005","Charmeleon","Fire","405","58","64","58","80","65","80"

value of counter 7
"006","Charizard","FireFlying","534","78","84","78","109","85","100"

value of counter 8
"006","CharizardMega Charizard X","FireDragon","634","78","130","111","130","85","100"

value of counter 9
"006","CharizardMega Charizard Y","FireFlying","634","78","104","78","159","115","100"

value of counter 10
"007","Squirtle","Water","314","44","48","

In [370]:
map(lambda x: x[1:-1].isdigit(), raw_pd.split('\n')[1].split(','))

[True, False, False, True, True, True, True, True, True, True]

In [371]:
import string
import re
line_counter = 0
list_of_lists = []
iter_list = []
print type(iter_list)
#print "iterlist positon 0", iter_list[0]
with open(pokedex_file, 'r') as f:
    while line_counter <= 10:
        for line in f:
            #print "this is the line being read by the iterator: ", line 
            #new_line = string.replace(line,'"',"'")
            #new_string = line.find(''\d'')
            #print new_string
            #print re.findall(r'(?<!\S)[+-]?\d+(?!\S)',line) 
            str2 =string.replace(line,'"',"'")
            list_feeder = str2.split('\n')
            #new_line = line.split('\n')
            #new_line2 = line.split('","')
            #print line.endswith('r'\n)
            #"true if it sees /n"    
            #print new_line
            #print "this is value of iter_list position", iter_list[0] 
            #print "type of list_of Lists", type(list_of_lists)
            line_counter +=1
            list_of_lists.append(list_feeder)
            #iter_list[0] = []
            #print line
            #prog = re.compile(r",")
            #result = prog.match(line)

print list_of_lists[:2]

#pattern = re.compile(r",")
#print pattern
#list_of_lists[2:3].find(pattern)




<type 'list'>
[["'PokedexNumber','Name','Type','Total','HP','Attack','Defense','SpecialAttack','SpecialDefense','Speed'", ''], ["'001','Bulbasaur','GrassPoison','318','45','49','49','65','65','45'", '']]


In [221]:
list_of_lists = []
with open(pokedex_file, 'r') as f:
    while i <=801:
        raw_pd_lines = f.readline(i)
        list_of_lists = eval('raw_pd_lines')
        i+=1
type(raw_pd_lines)
#type(list_of_lists)
#print raw_pd_lines
list_of_lists[:50]

[]

In [97]:
type(raw_pd)
#import re
#raw_pd_nobreaks = re.sub('\n', ', "!!!", ', raw_pd)

str

In [106]:
str1=string.replace(raw_pd,",,",",-1,") # there are actually no blank cells
str2 =string.replace(str1,'"',"'")
list_feeder = str2.split('\n')
type(list_feeder)

list

In [108]:
list_feeder[:50]


["'PokedexNumber','Name','Type','Total','HP','Attack','Defense','SpecialAttack','SpecialDefense','Speed'",
 "'001','Bulbasaur','GrassPoison','318','45','49','49','65','65','45'",
 "'002','Ivysaur','GrassPoison','405','60','62','63','80','80','60'",
 "'003','Venusaur','GrassPoison','525','80','82','83','100','100','80'",
 "'003','VenusaurMega Venusaur','GrassPoison','625','80','100','123','122','120','80'",
 "'004','Charmander','Fire','309','39','52','43','60','50','65'",
 "'005','Charmeleon','Fire','405','58','64','58','80','65','80'",
 "'006','Charizard','FireFlying','534','78','84','78','109','85','100'",
 "'006','CharizardMega Charizard X','FireDragon','634','78','130','111','130','85','100'",
 "'006','CharizardMega Charizard Y','FireFlying','634','78','104','78','159','115','100'",
 "'007','Squirtle','Water','314','44','48','65','50','64','43'",
 "'008','Wartortle','Water','405','59','63','80','65','80','58'",
 "'009','Blastoise','Water','530','79','83','100','85','105','78'",
 "'0

In [99]:
list_feeder[1:10]

['"001","Bulbasaur","GrassPoison","318","45","49","49","65","65","45"',
 '"002","Ivysaur","GrassPoison","405","60","62","63","80","80","60"',
 '"003","Venusaur","GrassPoison","525","80","82","83","100","100","80"',
 '"003","VenusaurMega Venusaur","GrassPoison","625","80","100","123","122","120","80"',
 '"004","Charmander","Fire","309","39","52","43","60","50","65"',
 '"005","Charmeleon","Fire","405","58","64","58","80","65","80"',
 '"006","Charizard","FireFlying","534","78","84","78","109","85","100"',
 '"006","CharizardMega Charizard X","FireDragon","634","78","130","111","130","85","100"',
 '"006","CharizardMega Charizard Y","FireFlying","634","78","104","78","159","115","100"']

In [126]:
"""list_of_lists = []
a_list = []
for i in range(801):
    a_list.append(i)
        list_of_lists.append((list(a_list), a_list[0]))
print list_of_lists


for i in range(801):
    list_of_lists_ = list_feeder[i]
    print list_of_lists[i]
    i+=1
"""
for i in list_feeder:
    d.append(list_of_lists[i])
list_of_lists[1] = list_feeder[2]

list_of_lists[:12]

IndexError: list index out of range

In [152]:
new_list[]
new_list[1] =list_feeder.pop([1])
    


SyntaxError: invalid syntax (<ipython-input-152-1c6c08edb73b>, line 1)

In [153]:
"""
import string
new_list_of_lists = ['PokedexNumber','Name','Type','Total','HP','Attack','Defense','SpecialAttack','SpecialDefense','Speed']
list_newrec_position = string.find("!!!",raw_pd_nobreaks)
print list_newrec_position
#list_newrec_position = string.find("!!!",raw_pd_nobreaks,)
#for i in raw_pd_nobreaks.count("!!!"):
#    new_list_of_lists.append()
#.append(raw_pd[i])
#    i+=1
#[10] = raw_pd[1:10]
#print new_list_of_lists"""


'\nimport string\nnew_list_of_lists = [\'PokedexNumber\',\'Name\',\'Type\',\'Total\',\'HP\',\'Attack\',\'Defense\',\'SpecialAttack\',\'SpecialDefense\',\'Speed\']\nlist_newrec_position = string.find("!!!",raw_pd_nobreaks)\nprint list_newrec_position\n#list_newrec_position = string.find("!!!",raw_pd_nobreaks,)\n#for i in raw_pd_nobreaks.count("!!!"):\n#    new_list_of_lists.append()\n#.append(raw_pd[i])\n#    i+=1\n#[10] = raw_pd[1:10]\n#print new_list_of_lists'

In [29]:
#import re
#string.replace(raw_pd,"'\'","^^^")
import string
string.replace(raw_pd_nobreaks,"NEWREC",'],[')
raw_pd_nobreaks[:4] + '-' + raw_pd_nobreaks[4:]
#pokedex_djs['Name'] = pokedex_djs['Name'].astype(str)
#pokedex_djs['Type'] = pokedex_djs['Type'].astype(str)
#pokedex_djs.dtypes

'"Pok-edexNumber","Name","Type","Total","HP","Attack","Defense","SpecialAttack","SpecialDefense","Speed", "!!!", "001","Bulbasaur","GrassPoison","318","45","49","49","65","65","45", "!!!", "002","Ivysaur","GrassPoison","405","60","62","63","80","80","60", "!!!", "003","Venusaur","GrassPoison","525","80","82","83","100","100","80", "!!!", "003","VenusaurMega Venusaur","GrassPoison","625","80","100","123","122","120","80", "!!!", "004","Charmander","Fire","309","39","52","43","60","50","65", "!!!", "005","Charmeleon","Fire","405","58","64","58","80","65","80", "!!!", "006","Charizard","FireFlying","534","78","84","78","109","85","100", "!!!", "006","CharizardMega Charizard X","FireDragon","634","78","130","111","130","85","100", "!!!", "006","CharizardMega Charizard Y","FireFlying","634","78","104","78","159","115","100", "!!!", "007","Squirtle","Water","314","44","48","65","50","64","43", "!!!", "008","Wartortle","Water","405","59","63","80","65","80","58", "!!!", "009","Blastoise","Wat

In [30]:
#pokedex_djs.describe()

In [31]:
#pokedex_djs.head(10)

In [32]:
#pokedex_djs.fillna(-1)

## 8.2 Parse the raw pokedex with list comprehensions¶
Perform the same parsing as above, but using only a single list comprehension instead of for loops. 

You may have nested list comprehensions within the main list comprehension! 

The output should be exactly the same.

Example output (first 3 sublists):

 ['PokedexNumber', 'Name', 'Type', 'Total', 'HP', 'Attack', 'Defense', 'SpecialAttack', 'SpecialDefense', 'Speed']
 [1.0, 'Bulbasaur', 'GrassPoison', 318.0, 45.0, 49.0, 49.0, 65.0, 65.0, 45.0]
 [2.0, 'Ivysaur', 'GrassPoison', 405.0, 60.0, 62.0, 63.0, 80.0, 80.0, 60.0]

## 9. Write a function to generate the full pokedex¶

Write a function that recreates the pokedex you made before, but with the data read in from the full pokemon file. The PokedexNumber should be used as the pokemon_id key values for the dictionary of pokemon.

Your function should:
Take the parsed pokedex information you created above as an argument.

Return a dictionary in the same format as your original pokedex you created before containing the information from the parsed full pokedex file.

To test the function, print out the pokemon with id = 100.

 Example output:

 {'Attack': 30.0,
  'Defense': 50.0,
  'HP': 40.0,
  'Name': 'Voltorb',
  'SpecialAttack': 55.0,
  'SpecialDefense': 55.0,
  'Speed': 100.0,
  'Total': 330.0,
  'Type': 'Electric'}


## 10. Write a function to generate a "filtered" pokedex¶
Your function should:
Take the parsed pokedex information you created above as an argument.
Take a dictionary as a parameter with keys matching the features of the Pokedex, filtering by exact match for string type values, and/or filter continuous variables specified value that is greater than or equal to the dictionary key parameter.
Return multiple elements from the Pokedex

Example:

* Only filter based on parameters passed

filter_options = {
    'Attack':   25,
    'Defense':  30,
    'Type':     'Electric'
}

* Return records with attack >= 24, defense >= 30, and type == "Electric"
* Also anticipate that other paramters can also be passed such as "SpecialAttack", "Speed", etc.
filtered_pokedex(pokedex_data, filter=filter_options)

 Example output:
 [{'Attack': 30.0,
  'Defense': 50.0,
  'HP': 40.0,
  'Name': 'Voltorb',
  'SpecialAttack': 55.0,
  'SpecialDefense': 55.0,
  'Speed': 100.0,
  'Total': 330.0,
  'Type': 'Electric'},
  {'Attack': 30.0,
  'Defense': 33.0,
  'HP': 32.0,
  'Name': 'Pikachu',
  'SpecialAttack': 55.0,
  'SpecialDefense': 55.0,
  'Speed': 100.0,
  'Total': 330.0,
  'Type': 'Electric'},
  ... etc
  ]


In [33]:
# Thought i was going to make a dataframe....
#pokedex_dframe_cols = ['PokedexNumber', 'Name', 'Type', 'Total', 'HP', 'Attack', 'Defense', 'SpecialAttack', 'SpecialDefense', 'Speed']
#pokedex_dframe = pandas.dataframe(columns = pokedex_dframe_cols, index = index)
#for in in range(raw_pd.count("\n")):


In [179]:
# Here's some testing to understand what was happening with my list comprehension

list1 = [["rob", "bill", "sam"], ['rachel', 'barb', 'susan']]
list1[1]
piece = [["r", "b", "s"], ['c', 'a', 'm'], [1, 2, 6]]
i = 1
print list1[1], "this is initial value of item 1 in list1"
print piece[2], "this is the 3rd item in piece list"

>> string = '[1,2,3]'
>>> list = eval(string)
>>> list
[1, 2, 3]#for i in range(3):
#    i+=1
#    list1.extend(piece[i])
    
list1[:5]

['rachel', 'barb', 'susan'] this is initial value of item 1 in list1
[1, 2, 6] this is the 3rd item in piece list


IndexError: list index out of range

In [168]:
"""import re
raw_pd_nobreaks = re.sub('[\n]', ', "NEWREC", ', raw_pd)"""

'import re\nraw_pd_nobreaks = re.sub(\'[\n]\', \', "NEWREC", \', raw_pd)'